version: '3.8'

services:

  web:
    container_name: web-cont
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn ni_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    container_name: db-cont
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
